export interface Word {
  en: string;
  th: string;
}

export const WORDS: Word[] = [
  { en: "Agenda", th: "วาระการประชุม" },
  { en: "Strategy", th: "กลยุทธ์" },
  { en: "Implementation", th: "การดำเนินการ" },
  { en: "Objective", th: "วัตถุประสงค์" },
  { en: "Priority", th: "ลำดับความสำคัญ" },
  { en: "Proposal", th: "ข้อเสนอ" },
  { en: "Executive", th: "ผู้บริหาร" },
  { en: "Benchmark", th: "เกณฑ์มาตรฐาน" },
  { en: "Feasibility", th: "ความเป็นไปได้" },
  { en: "Efficiency", th: "ประสิทธิภาพ" },
  { en: "Productivity", th: "ผลิตภาพ" },
  { en: "Risk", th: "ความเสี่ยง" },
  { en: "Restructure", th: "ปรับโครงสร้าง" },
  { en: "Stakeholder", th: "ผู้มีส่วนได้ส่วนเสีย" },
  { en: "Leadership", th: "ความเป็นผู้นำ" },
  { en: "Delegation", th: "การมอบหมายงาน" },
  { en: "Milestone", th: "หมุดหมายความสำเร็จ" },
  { en: "Optimization", th: "การปรับให้เหมาะสมที่สุด" },
  { en: "Contingency", th: "แผนสำรอง" },
  { en: "Alignment", th: "ความสอดคล้องกัน" },
  { en: "Memorandum (Memo)", th: "บันทึกข้อความ" },
  { en: "Attachment", th: "ไฟล์แนบ" },
  { en: "Inquiry", th: "การสอบถาม" },
  { en: "Clarify", th: "ชี้แจง" },
  { en: "Feedback", th: "ข้อเสนอแนะ" },
  { en: "Deadline", th: "กำหนดส่ง" },
  { en: "Minutes", th: "รายงานการประชุม" },
  { en: "Confirm", th: "ยืนยัน" },
  { en: "Schedule", th: "กำหนดการ" },
  { en: "Reschedule", th: "เปลี่ยนกำหนดการ" },
  { en: "Collaborate", th: "ร่วมมือ" },
  { en: "Follow-up", th: "การติดตามผล" },
  { en: "Urgent", th: "ด่วน" },
  { en: "Forward", th: "ส่งต่อ" },
  { en: "Acknowledge", th: "รับทราบ" },
  { en: "Correspondence", th: "การติดต่อทางจดหมาย" },
  { en: "Briefing", th: "การบรีฟงาน" },
  { en: "Conference", th: "การประชุมใหญ่" },
  { en: "Consensus", th: "ความเห็นพ้องต้องกัน" },
  { en: "Extension", th: "การขยายเวลา / สายแยก" },
  { en: "Budget", th: "งบประมาณ" },
  { en: "Revenue", th: "รายได้" },
  { en: "Expenditure", th: "ค่าใช้จ่าย" },
  { en: "Profit", th: "กำไร" },
  { en: "Loss", th: "ขาดทุน" },
  { en: "Invoice", th: "ใบแจ้งหนี้" },
  { en: "Receipt", th: "ใบเสร็จรับเงิน" },
  { en: "Asset", th: "สินทรัพย์" },
  { en: "Liability", th: "หนี้สิน" },
  { en: "Cash flow", th: "กระแสเงินสด" },
  { en: "Audit", th: "การตรวจสอบบัญชี" },
  { en: "Refund", th: "การคืนเงิน" },
  { en: "Margin", th: "อัตรากำไร" },
  { en: "Investment", th: "การลงทุน" },
  { en: "Overhead", th: "ค่าใช้จ่ายดำเนินงาน" },
  { en: "Balance", th: "ยอดคงเหลือ" },
  { en: "Depreciation", th: "ค่าเสื่อมราคา" },
  { en: "Capital", th: "เงินทุน" },
  { en: "Forecast", th: "การคาดการณ์" },
  { en: "ROI (Return on Investment)", th: "ผลตอบแทนจากการลงทุน" },
  { en: "Campaign", th: "แคมเปญ" },
  { en: "Target market", th: "ตลาดเป้าหมาย" },
  { en: "Brand awareness", th: "การรับรู้แบรนด์" },
  { en: "Conversion", th: "การแปลงสภาพ (ลูกค้า)" },
  { en: "Promotion", th: "การส่งเสริมการขาย" },
  { en: "Negotiation", th: "การเจรจาต่อรอง" },
  { en: "Client", th: "ลูกค้า" },
  { en: "Prospect", th: "ลูกค้าคาดหวัง" },
  { en: "Competitor", th: "คู่แข่ง" },
  { en: "Demographics", th: "ประชากรศาสตร์" },
  { en: "Wholesale", th: "ขายส่ง" },
  { en: "Retail", th: "ขายปลีก" },
  { en: "Commission", th: "ค่านายหน้า" },
  { en: "Discount", th: "ส่วนลด" },
  { en: "B2B (Business to Business)", th: "ธุรกิจแบบ B2B" },
  { en: "Launch", th: "การเปิดตัว" },
  { en: "Penetration", th: "การเจาะตลาด" },
  { en: "Retention", th: "การรักษาลูกค้า" },
  { en: "Pitch", th: "การนำเสนอขาย" },
  { en: "Engagement", th: "การมีส่วนร่วม" },
  { en: "Recruitment", th: "การสรรหาบุคลากร" },
  { en: "Candidate", th: "ผู้สมัคร" },
  { en: "Onboarding", th: "การรับพนักงานใหม่เข้าทำงาน" },
  { en: "Performance", th: "ประสิทธิภาพการทำงาน" },
  { en: "Appraisal", th: "การประเมินผล" },
  { en: "Probation", th: "การทดลองงาน" },
  { en: "Contract", th: "สัญญา" },
  { en: "Clause", th: "ข้อกำหนด" },
  { en: "NDA (Non-Disclosure Agreement)", th: "ข้อตกลงไม่เปิดเผยข้อมูล" },
  { en: "Compliance", th: "การปฏิบัติตามกฎระเบียบ" },
  { en: "Compensation", th: "ค่าตอบแทน" },
  { en: "Benefit", th: "สวัสดิการ" },
  { en: "Promotion (Career)", th: "การเลื่อนตำแหน่ง" },
  { en: "Resignation", th: "การลาออก" },
  { en: "Severance", th: "ค่าชดเชยการเลิกจ้าง" },
  { en: "Termination", th: "การสิ้นสุด" },
  { en: "Outsource", th: "การจ้างคนนอก" },
  { en: "Turnover", th: "อัตราการหมุนเวียนของพนักงาน" },
  { en: "Workforce", th: "กำลังคน / พนักงาน" },
  { en: "Headcount", th: "จำนวนพนักงาน" },
];
